/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Sergi
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        ngOnitEntries();
        ngOnitStrongPlate();
        ngOnitDrinks();
        ngOnitPostres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane8 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        panelMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        lblSalchipapa = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblChicharrones = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblArepitas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        panelPlato1 = new javax.swing.JPanel();
        lblPlato1 = new javax.swing.JLabel();
        panelPlato3 = new javax.swing.JPanel();
        lblPlato3 = new javax.swing.JLabel();
        panelPlato2 = new javax.swing.JPanel();
        lblPlato2 = new javax.swing.JLabel();
        panelPlato4 = new javax.swing.JPanel();
        lblPlato4 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblPrecio2 = new javax.swing.JLabel();
        lblPrecio3 = new javax.swing.JLabel();
        lblPrecio4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        boxPfuerte = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jPanel15 = new javax.swing.JPanel();
        lblColom = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblPepsi = new javax.swing.JLabel();
        panelCocaCola = new javax.swing.JPanel();
        lblCoca = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblMaracuya = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblMora = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        lblMango = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblMoraMango = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        lblmaraCumango = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblMaraMora = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jbl = new javax.swing.JPanel();
        lblPostre2 = new javax.swing.JLabel();
        jpam = new javax.swing.JPanel();
        lblPostre1 = new javax.swing.JLabel();
        jbls = new javax.swing.JPanel();
        lblPostre3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblPostre4 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMenu.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 280));

        jDesktopPane2.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 330, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ACME");
        jDesktopPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton1.setText("Pedir Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        jTabbedPane1.addTab("Menu", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalchipapa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalchipapa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jDesktopPane3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 150));

        jPanel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel8KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChicharrones, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblChicharrones, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jDesktopPane3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, 150));

        jPanel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel9KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblArepitas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblArepitas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jDesktopPane3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 150, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PRECIO");
        jDesktopPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PRECIO");
        jDesktopPane3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("PRECIO");
        jDesktopPane3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 60, 20));

        jPanel2.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        jTabbedPane1.addTab("Entradas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlato1.setText("jLabel13");

        javax.swing.GroupLayout panelPlato1Layout = new javax.swing.GroupLayout(panelPlato1);
        panelPlato1.setLayout(panelPlato1Layout);
        panelPlato1Layout.setHorizontalGroup(
            panelPlato1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelPlato1Layout.setVerticalGroup(
            panelPlato1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane4.add(panelPlato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 110));

        lblPlato3.setText("jLabel15");

        javax.swing.GroupLayout panelPlato3Layout = new javax.swing.GroupLayout(panelPlato3);
        panelPlato3.setLayout(panelPlato3Layout);
        panelPlato3Layout.setHorizontalGroup(
            panelPlato3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelPlato3Layout.setVerticalGroup(
            panelPlato3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane4.add(panelPlato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 110));

        lblPlato2.setText("jLabel14");

        javax.swing.GroupLayout panelPlato2Layout = new javax.swing.GroupLayout(panelPlato2);
        panelPlato2.setLayout(panelPlato2Layout);
        panelPlato2Layout.setHorizontalGroup(
            panelPlato2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelPlato2Layout.setVerticalGroup(
            panelPlato2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane4.add(panelPlato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, 110));

        lblPlato4.setText("jLabel16");

        javax.swing.GroupLayout panelPlato4Layout = new javax.swing.GroupLayout(panelPlato4);
        panelPlato4.setLayout(panelPlato4Layout);
        panelPlato4Layout.setHorizontalGroup(
            panelPlato4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelPlato4Layout.setVerticalGroup(
            panelPlato4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPlato4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jDesktopPane4.add(panelPlato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 110, 100));

        lblPrecio1.setText("PRECIO");
        jDesktopPane4.add(lblPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, 20));

        lblPrecio2.setText("PRECIO");
        jDesktopPane4.add(lblPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        lblPrecio3.setText("PRECIO");
        jDesktopPane4.add(lblPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        lblPrecio4.setText("PRECIO");
        jDesktopPane4.add(lblPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        boxPfuerte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carnivoro", "vegetariano" }));
        boxPfuerte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxPfuerteItemStateChanged(evt);
            }
        });

        jDesktopPane9.setLayer(boxPfuerte, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boxPfuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(boxPfuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane9)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 70));

        jPanel3.add(jDesktopPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        jTabbedPane1.addTab("PlatoFuerte", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblColom.setText("jLabel6");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblColom, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblColom, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 110, 110));

        lblPepsi.setText("jLabel7");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, 110));

        lblCoca.setText("jLabel5");

        javax.swing.GroupLayout panelCocaColaLayout = new javax.swing.GroupLayout(panelCocaCola);
        panelCocaCola.setLayout(panelCocaColaLayout);
        panelCocaColaLayout.setHorizontalGroup(
            panelCocaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoca, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelCocaColaLayout.setVerticalGroup(
            panelCocaColaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCoca, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(panelCocaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 110));

        lblMaracuya.setText("jLabel14");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaracuya, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaracuya, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, 110));

        lblMora.setText("jLabel13");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMora, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMora, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, 110));

        lblMango.setText("jLabel8");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMango, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMango, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 110));

        lblMoraMango.setText("jLabel15");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMoraMango, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMoraMango, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 90));

        lblmaraCumango.setText("jLabel16");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmaraCumango, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmaraCumango, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 110, 90));

        lblMaraMora.setText("jLabel17");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaraMora, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMaraMora, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jDesktopPane5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 110, 90));

        jPanel4.add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        jTabbedPane1.addTab("Bebidas", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPostre2.setText("jLabel7");

        javax.swing.GroupLayout jblLayout = new javax.swing.GroupLayout(jbl);
        jbl.setLayout(jblLayout);
        jblLayout.setHorizontalGroup(
            jblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jblLayout.setVerticalGroup(
            jblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jDesktopPane6.add(jbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 130));

        lblPostre1.setText("jLabel6");

        javax.swing.GroupLayout jpamLayout = new javax.swing.GroupLayout(jpam);
        jpam.setLayout(jpamLayout);
        jpamLayout.setHorizontalGroup(
            jpamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpamLayout.setVerticalGroup(
            jpamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jDesktopPane6.add(jpam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 150, 140));

        lblPostre3.setText("jLabel8");

        javax.swing.GroupLayout jblsLayout = new javax.swing.GroupLayout(jbls);
        jbls.setLayout(jblsLayout);
        jblsLayout.setHorizontalGroup(
            jblsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jblsLayout.setVerticalGroup(
            jblsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jDesktopPane6.add(jbls, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 140, 140));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Precio");
        jDesktopPane6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Precio");
        jDesktopPane6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Precio");
        jDesktopPane6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Precio");
        jDesktopPane6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        lblPostre4.setText("jLabel6");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPostre4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jDesktopPane6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 130));

        jPanel6.add(jDesktopPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        jTabbedPane1.addTab("Postres", jPanel6);

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("PRECIO");
        jDesktopPane7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 114, 41));

        jButton4.setText("PAGAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 110, 40));

        jPanel26.add(jDesktopPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        jTabbedPane1.addTab("Menu", jPanel26);

        jDesktopPane1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9KeyPressed

    private void jPanel8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8KeyPressed

    private void jPanel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7KeyPressed

    private void boxPfuerteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxPfuerteItemStateChanged
        // TODO add your handling code here:
        
        if(this.boxPfuerte.getSelectedItem().toString() == "carnivoro"){
           lblPlato4.setVisible(true);
            ngOnitStrongPlate();
        }
        if(this.boxPfuerte.getSelectedItem().toString() == "vegetariano"){
        lblPlato4.setVisible(false);
        setImage(lblPlato1, "src/image/Albondigas.png");
        setImage(lblPlato2, "src/image/lasañaMaduro.png");
        setImage(lblPlato3, "src/image/sopaTomate.png");
        }
       
    }//GEN-LAST:event_boxPfuerteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
    private void notVisible(JLabel jlabel,JPanel jpanel){
        jlabel.setVisible(false);
        jpanel.setVisible(false);
    }
    public void setImage(JLabel label,String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(label.getWidth(), 
                label.getHeight(),
                Image.SCALE_DEFAULT
                )
        );
        label.setIcon(icon);
        this.repaint();
        
    }
    
   private void ngOnitEntries(){
        setImage(this.lblMenu,"src/image/acmen.png"); 
        setImage(this.lblSalchipapa,"src/image/salchi.png"); 
        setImage(this.lblChicharrones,"src/image/chicarr.png"); 
        setImage(this.lblArepitas,"src/image/arep.png");   
   }
   private void ngOnitStrongPlate(){
        setImage(lblPlato1, "src/image/carne.png");
        setImage(lblPlato2, "src/image/pollo.png");
        setImage(lblPlato3, "src/image/pescado.png");
        setImage(lblPlato4, "src/image/mariscos.png"); 
   }
   private void ngOnitPostres(){
        setImage(lblPostre1, "src/image/postre1.png");
        setImage(lblPostre2, "src/image/postre2.png");
        setImage(lblPostre3, "src/image/postre3.png");
        setImage(lblPostre4, "src/image/postre4.png"); 
   }
   private void ngOnitDrinks(){
        setImage(lblCoca, "src/image/cocaCola.png");
        setImage(lblColom, "src/image/colombiana.png");
        setImage(lblPepsi, "src/image/pepsi.png");
        setImage(lblMango, "src/image/jugoMango.png");
        setImage(lblMora, "src/image/jugoMora.png");
        setImage(lblMaracuya, "src/image/jugoMaracuya.png");
        setImage(lblMaraMora, "src/image/maraMora.png");
        setImage(lblmaraCumango, "src/image/maracumango.png");
        setImage(lblMoraMango, "src/image/moraMango.png");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPfuerte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jbl;
    private javax.swing.JPanel jbls;
    private javax.swing.JPanel jpam;
    private javax.swing.JLabel lblArepitas;
    private javax.swing.JLabel lblChicharrones;
    private javax.swing.JLabel lblCoca;
    private javax.swing.JLabel lblColom;
    private javax.swing.JLabel lblMango;
    private javax.swing.JLabel lblMaraMora;
    private javax.swing.JLabel lblMaracuya;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMora;
    private javax.swing.JLabel lblMoraMango;
    private javax.swing.JLabel lblPepsi;
    private javax.swing.JLabel lblPlato1;
    private javax.swing.JLabel lblPlato2;
    private javax.swing.JLabel lblPlato3;
    private javax.swing.JLabel lblPlato4;
    private javax.swing.JLabel lblPostre1;
    private javax.swing.JLabel lblPostre2;
    private javax.swing.JLabel lblPostre3;
    private javax.swing.JLabel lblPostre4;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrecio4;
    private javax.swing.JLabel lblSalchipapa;
    private javax.swing.JLabel lblmaraCumango;
    private javax.swing.JPanel panelCocaCola;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPlato1;
    private javax.swing.JPanel panelPlato2;
    private javax.swing.JPanel panelPlato3;
    private javax.swing.JPanel panelPlato4;
    // End of variables declaration//GEN-END:variables
}
